



# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Raviv Gilady\Desktop\temp dir\node_details.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nodeeditor.utils import dumpException


class Ui_Node_Details(object):
    def __init__(self,callback):
        super().__init__()
        self.actors=[]
        self.actors_count=0
        self.callback=callback
    def setupUi(self, Node_Details):
        Node_Details.setObjectName("Node_Details")
        Node_Details.resize(371, 645)
        self.widget = QtWidgets.QWidget(Node_Details)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 371, 641))
        self.widget.setObjectName("widget")
        self.save_details_btn = QtWidgets.QPushButton(self.widget)
        self.save_details_btn.setGeometry(QtCore.QRect(40, 470, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.save_details_btn.setFont(font)
        self.save_details_btn.setObjectName("save_details_btn")
        self.save_details_btn.clicked.connect(self.save_datails)

        self.actors_comboBox = QtWidgets.QComboBox(self.widget)
        self.actors_comboBox.setGeometry(QtCore.QRect(40, 240, 171, 31))
        self.actors_comboBox.setObjectName("actors_comboBox")
        self.actors_comboBox.addItem("")
        self.actors_comboBox.addItem("")
        self.actors_comboBox.addItem("")
        self.actors_comboBox.addItem("")
        self.actors_comboBox.addItem("")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(40, 290, 171, 161))
        self.listWidget.setObjectName("listWidget")
        self.add_actor_btn = QtWidgets.QPushButton(self.widget)
        self.add_actor_btn.setGeometry(QtCore.QRect(220, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.add_actor_btn.setFont(font)
        self.add_actor_btn.setObjectName("add_actor_btn")
        self.add_actor_btn.clicked.connect(self.add_line)
        self.actor_in_charge_combo = QtWidgets.QComboBox(self.widget)
        self.actor_in_charge_combo.setGeometry(QtCore.QRect(40, 150, 171, 31))
        self.actor_in_charge_combo.setObjectName("actor_in_charge_combo")
        self.actor_in_charge_combo.addItem("")
        self.actor_in_charge_combo.addItem("")
        self.actor_in_charge_combo.addItem("")
        self.actor_in_charge_combo.addItem("")
        self.actor_in_charge_combo.addItem("")
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setGeometry(QtCore.QRect(40, 210, 131, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setGeometry(QtCore.QRect(40, 120, 151, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.node_title = QtWidgets.QLineEdit(self.widget)
        self.node_title.setGeometry(QtCore.QRect(40, 69, 141, 31))
        self.node_title.setObjectName("node_title")
        self.node_time = QtWidgets.QLineEdit(self.widget)
        self.node_time.setGeometry(QtCore.QRect(40, 20, 141, 31))
        self.node_time.setObjectName("node_title")

        self.retranslateUi(Node_Details)
        QtCore.QMetaObject.connectSlotsByName(Node_Details)

    def retranslateUi(self, Node_Details):
        _translate = QtCore.QCoreApplication.translate
        Node_Details.setWindowTitle(_translate("Node_Details", "Dialog"))
        self.save_details_btn.setText(_translate("Node_Details", "Save Details"))
        self.actors_comboBox.setItemText(0, _translate("Node_Details", "Nurse"))
        self.actors_comboBox.setItemText(1, _translate("Node_Details", "Doctor"))
        self.actors_comboBox.setItemText(2, _translate("Node_Details", "Investigator"))
        self.actors_comboBox.setItemText(3, _translate("Node_Details", "Participant"))
        self.actors_comboBox.setItemText(4, _translate("Node_Details", "Lab Technician"))
        self.add_actor_btn.setText(_translate("Node_Details", "Add Actor"))
        self.actor_in_charge_combo.setItemText(0, _translate("Node_Details", "Nurse"))
        self.actor_in_charge_combo.setItemText(1, _translate("Node_Details", "Doctor"))
        self.actor_in_charge_combo.setItemText(2, _translate("Node_Details", "Investigator"))
        self.actor_in_charge_combo.setItemText(3, _translate("Node_Details", "Participant"))
        self.actor_in_charge_combo.setItemText(4, _translate("Node_Details", "Lab Technician"))
        self.label_4.setText(_translate("Node_Details", "Add Actors"))
        self.label_5.setText(_translate("Node_Details", "Choose Actor In Charge"))
        self.node_title.setPlaceholderText(_translate("Node_Details", "Node Title"))
        self.node_time.setPlaceholderText(_translate("Node_Details", "Node Time"))

    def add_line(self):
        try:
            self.actors.append(self.actors_comboBox.currentText())
            _translate = QtCore.QCoreApplication.translate
            item = QtWidgets.QListWidgetItem()
            self.listWidget.addItem(item)
            item = self.listWidget.item(self.actors_count)
            item.setText(_translate("Node_Details", f"{self.actors_comboBox.currentText()}"))
            self.actors_count += 1
        except Exception as e:
            dumpException(e)

    def save_datails(self):
        self.callback({"actors" : self.actors, "title": self.node_title.text(), "actor in charge" :\
            self.actor_in_charge_combo.currentText(), "time": self.node_time.text()})
if __name__ == "__main__":
    pass
    # import sys
    # app = QtWidgets.QApplication(sys.argv)
    # Node_Details = QtWidgets.QDialog()
    # # ui = Ui_Node_Details()
    # ui.setupUi(Node_Details)
    # Node_Details.show()
    # sys.exit(app.exec_())
