# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Raviv Gilady\Desktop\computers\Clinical_Trails_Automation\Workflow Editor\Windows\Questions Windows\open_question.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_OpenQuestion(object):
    def __init__(self,callback):
        super().__init__()
        self.callback= callback
    def setupUi(self, OpenQuestion):
        OpenQuestion.setObjectName("OpenQuestion")
        OpenQuestion.resize(556, 243)
        self.window= OpenQuestion

        self.widget = QtWidgets.QWidget(OpenQuestion)
        self.widget.setObjectName("centralwidget")
        self.question_txt = QtWidgets.QTextEdit(self.widget)
        self.question_txt.setGeometry(QtCore.QRect(10, 30, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.question_txt.setFont(font)
        self.question_txt.setObjectName("question_txt")
        self.finish_btn = QtWidgets.QPushButton(self.widget)
        self.finish_btn.setGeometry(QtCore.QRect(10, 160, 131, 61))
        self.finish_btn.setObjectName("finish_btn")
        self.finish_btn.clicked.connect(self.save_question)

        self.discard_btn = QtWidgets.QPushButton(self.widget)
        self.discard_btn.setGeometry(QtCore.QRect(160, 160, 131, 61))
        self.discard_btn.setObjectName("discard_btn")
        self.discard_btn.clicked.connect(self.exit_window)

        #OpenQuestion.setCentralWidget(self.widget)

        self.retranslateUi(OpenQuestion)
        QtCore.QMetaObject.connectSlotsByName(OpenQuestion)

    def retranslateUi(self, OpenQuestion):
        _translate = QtCore.QCoreApplication.translate
        OpenQuestion.setWindowTitle(_translate("OpenQuestion", "Open Question"))
        self.question_txt.setPlaceholderText(_translate("OpenQuestion", "Plese Enter Your Question"))
        self.finish_btn.setText(_translate("OpenQuestion", "Finish Question"))
        self.discard_btn.setText(_translate("OpenQuestion", "Discard"))

    def save_question(self):
        print("DEBUG")
        # self.all_questions[self.question_txt.toPlainText()] =  {"type" : "open"}
        self.callback({"text" : self.question_txt.toPlainText(), "type" : "open"})
        self.exit_window()
    def exit_window(self):
        self.window.close()
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    OpenQuestion = QtWidgets.QMainWindow()
    ui = Ui_OpenQuestion({})
    ui.setupUi(OpenQuestion)
    OpenQuestion.show()
    sys.exit(app.exec_())
