# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './Workflow Editor/Windows/Questions Windows/question with options.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.
from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MultipleChoiceQuestionAdd(object):
    def __init__(self,qustions,type):
        super().__init__()
        self.options=[]
        self.num_of_visible_options=0
        self.func=qustions
        self.type=type
    def setupUi(self, MultipleChoiceQuestionAdd):
        MultipleChoiceQuestionAdd.setObjectName("MultipleChoiceQuestionAdd")
        MultipleChoiceQuestionAdd.resize(556, 767)
        self.window= MultipleChoiceQuestionAdd
        self.widget = QtWidgets.QWidget(MultipleChoiceQuestionAdd)
        self.widget.setObjectName("centralwidget")
        self.question_txt = QtWidgets.QTextEdit(self.widget)
        self.question_txt.setGeometry(QtCore.QRect(10, 30, 511, 101))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.question_txt.setFont(font)
        self.question_txt.setObjectName("question_txt")
        self.groupBox = QtWidgets.QGroupBox(self.widget)
        self.groupBox.setGeometry(QtCore.QRect(20, 210, 381, 461))
        self.groupBox.setObjectName("groupBox")
        self.add_default_options()
        self.add_option_btn = QtWidgets.QPushButton(self.groupBox)
        self.add_option_btn.setGeometry(QtCore.QRect(220, 30, 151, 51))
        self.add_option_btn.setObjectName("add_option_btn")
        self.add_option_btn.clicked.connect(self.add_option)
        self.remove_last_option_btn = QtWidgets.QPushButton(self.groupBox)
        self.remove_last_option_btn.setGeometry(QtCore.QRect(220, 100, 151, 51))
        self.remove_last_option_btn.setObjectName("remove_last_option_btn")
        self.remove_last_option_btn.clicked.connect(self.remove_option)

        self.label = QtWidgets.QLabel(self.widget)
        self.label.setGeometry(QtCore.QRect(10, 140, 241, 61))
        self.label.setObjectName("label")

        self.finish_btn = QtWidgets.QPushButton(self.widget)
        self.finish_btn.setGeometry(QtCore.QRect(20, 680, 131, 61))
        self.finish_btn.setObjectName("finish_btn")
        self.finish_btn.clicked.connect(self.save_question)

        self.discard_btn = QtWidgets.QPushButton(self.widget)
        self.discard_btn.setGeometry(QtCore.QRect(170, 680, 131, 61))
        self.discard_btn.setObjectName("discard_btn")
        self.discard_btn.clicked.connect(self.exit_window)

        self.feedback_label = QtWidgets.QLabel(self.widget)
        self.feedback_label.setGeometry(QtCore.QRect(10, 190, 161, 16))
        self.feedback_label.setStyleSheet("color:rgb(255, 0, 0)")
        self.feedback_label.setText("")
        self.feedback_label.setObjectName("feedback_label")

        #MultipleChoiceQuestionAdd.setCentralWidget(self.widget)

        self.retranslateUi(MultipleChoiceQuestionAdd)
        QtCore.QMetaObject.connectSlotsByName(MultipleChoiceQuestionAdd)
    def add_default_options(self):
        self.num_of_visible_options=2
        for i in range (6):
            self.options.append(QtWidgets.QLineEdit(self.groupBox))

            # for_debug_purpose_option =QtWidgets.QLineEdit(self.groupBox)
            self.options[i].setGeometry(QtCore.QRect(30, 30+(i*70), 151, 41))
            self.options[i].setObjectName(f"option_{i}")
            if i>=self.num_of_visible_options:
                self.options[i].setVisible(False)

    def clean_feedback(self):
        self.feedback_label.setText("")
    def add_option(self):
        self.clean_feedback()
        if self.num_of_visible_options == 6:
            self.feedback_label.setText("Cannot add more than 5 options!")
        else:
            self.options[self.num_of_visible_options].setVisible(True)
            self.num_of_visible_options += 1
    def remove_option(self):
        self.clean_feedback()
        if self.num_of_visible_options == 2:
            self.feedback_label.setText("Cannot have less than 2 options!")
        else:
            self.options[self.num_of_visible_options-1].setVisible(False)
            self.options[self.num_of_visible_options - 1].setText("")
            self.num_of_visible_options -= 1
    def save_question(self):
        q={"text" :self.question_txt.toPlainText(),
            "options":[option.text() for option in self.options if option.isVisible()] ,
            "type" : self.type }
        self.func(q)

        self.exit_window()
    def exit_window(self):
        self.window.close()
    def retranslateUi(self, MultipleChoiceQuestionAdd):
        _translate = QtCore.QCoreApplication.translate
        MultipleChoiceQuestionAdd.setWindowTitle(_translate("MultipleChoiceQuestionAdd", "Multiple Choices Question Add"))
        self.question_txt.setPlaceholderText(_translate("MultipleChoiceQuestionAdd", "Please Enter Your Question"))
        self.groupBox.setTitle(_translate("MultipleChoiceQuestionAdd", "Options"))
        self.add_option_btn.setText(_translate("MultipleChoiceQuestionAdd", "Add Option"))
        self.remove_last_option_btn.setText(_translate("MultipleChoiceQuestionAdd", "Remove Last  Option"))
        self.label.setText(_translate("MultipleChoiceQuestionAdd", "Please Enter Your Options Below"))
        self.finish_btn.setText(_translate("MultipleChoiceQuestionAdd", "Finish Question"))
        self.discard_btn.setText(_translate("MultipleChoiceQuestionAdd", "Discard"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MultipleChoiceQuestionAdd = QtWidgets.QMainWindow()
    ui = Ui_MultipleChoiceQuestionAdd({},"radio")
    ui.setupUi(MultipleChoiceQuestionAdd)
    MultipleChoiceQuestionAdd.show()
    # MultipleChoiceQuestionAdd.hide()
    sys.exit(app.exec_())
