# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\string_node.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nodeeditor.utils import dumpException
from node_details_simple import Ui_node_details_simple


class Ui_string_node(object):
    def __init__(self, callback, data=None):
        super().__init__()
        self.details = {}
        self.callback = callback
        self.data = data

    def setupUi(self, Ui_stringNode):
        Ui_stringNode.setObjectName("Ui_stringNode")
        Ui_stringNode.resize(674, 339)
        self.centralwidget = QtWidgets.QWidget(Ui_stringNode)
        self.centralwidget.setObjectName("centralwidget")

        self.save_string_node = QtWidgets.QPushButton(self.centralwidget)
        self.save_string_node.setGeometry(QtCore.QRect(30, 250, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.save_string_node.setFont(font)
        self.save_string_node.setObjectName("save_string_node")
        self.save_string_node.clicked.connect(self.save_finish)

        self.discard_button = QtWidgets.QPushButton(self.centralwidget)
        self.discard_button.setGeometry(QtCore.QRect(240, 250, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.discard_button.setFont(font)
        self.discard_button.setObjectName("discard_button")
        self.discard_button.clicked.connect(self.discard)

        self.add_node_details = QtWidgets.QPushButton(self.centralwidget)
        self.add_node_details.setGeometry(QtCore.QRect(440, 250, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.add_node_details.setFont(font)
        self.add_node_details.setObjectName("save_questionnaire_btn_3")
        self.add_node_details.clicked.connect(self.add_node_details_simple)

        self.input_line = QtWidgets.QLineEdit(self.centralwidget)
        self.input_line.setGeometry(QtCore.QRect(30, 110, 361, 31))
        self.input_line.setObjectName("lineEdit")


        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(30, 50, 271, 51))
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        # Ui_stringNode.setCentralWidget(self.centralwidget)

        self.retranslateUi(Ui_stringNode)
        QtCore.QMetaObject.connectSlotsByName(Ui_stringNode)

        if self.data is not None:
            self.fill_data()

    def retranslateUi(self, Ui_stringNode):
        _translate = QtCore.QCoreApplication.translate
        Ui_stringNode.setWindowTitle(_translate("Ui_stringNode", "Enter String"))
        self.save_string_node.setText(_translate("Ui_stringNode", "Save"))
        self.discard_button.setText(_translate("Ui_stringNode", "Discard"))
        self.add_node_details.setText(_translate("Ui_stringNode", "Add Node Details"))
        self.label.setText(_translate("Ui_stringNode", "Enter String Value:"))


    def add_node_details_simple(self):
        try:
            self.new_window = QtWidgets.QDialog()
            ui = Ui_node_details_simple(self.callback_from_node_details,self.details)
            ui.setupUi(self.new_window)
            self.new_window.exec_()
        except Exception as e:
            dumpException(e)


    def callback_from_node_details(self, details):
        self.new_window.close()
        if details is not None:
            self.details = details

    def save_finish(self):
        try:
            self.callback({"node_details": self.details, "text": self.input_line.text()})
        except Exception as e:
            dumpException(e)

    def discard(self):
        try:
            self.callback(None)
        except Exception as e:
            dumpException(e)

    def fill_data(self):
        self.details = self.data["node_details"]
        self.input_line.setText(self.data["text"])


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Ui_stringNode = QtWidgets.QMainWindow()
    ui = Ui_string_node(None)
    ui.setupUi(Ui_stringNode)
    Ui_stringNode.show()
    sys.exit(app.exec_())
