# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\Raviv Gilady\Desktop\temp dir\tests_builder.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nodeeditor.utils import dumpException
from add_test import Ui_Add_Test

class Ui_Test_Builder(object):
    def __init__(self,callback):
        super().__init__()
        self.callback=callback
        self._num_of_tests = 0
        self._test_list = []
    def setupUi(self, Test_Builder):
        Test_Builder.setObjectName("Test_Builder")
        Test_Builder.resize(563, 640)
        self.widget = QtWidgets.QWidget(Test_Builder)
        self.window = Test_Builder
        self.widget.setGeometry(QtCore.QRect(-1, -1, 561, 641))
        self.widget.setObjectName("widget")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(20, 60, 301, 471))
        self.listWidget.setObjectName("listWidget")
        self.save_test_btn = QtWidgets.QPushButton(self.widget)
        self.save_test_btn.setGeometry(QtCore.QRect(20, 560, 201, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.save_test_btn.setFont(font)
        self.save_test_btn.setObjectName("save_test_btn")
        self.save_test_btn.clicked.connect(self.save_finish)


        self.discard_btn = QtWidgets.QPushButton(self.widget)
        self.discard_btn.setGeometry(QtCore.QRect(230, 560, 191, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.discard_btn.setFont(font)
        self.discard_btn.setObjectName("discard_btn")
        self.discard_btn.clicked.connect(self.discard)

        self.add_test_btn = QtWidgets.QPushButton(self.widget)
        self.add_test_btn.setGeometry(QtCore.QRect(340, 250, 171, 51))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.add_test_btn.setFont(font)
        self.add_test_btn.setObjectName("add_test_btn")
        self.add_test_btn.clicked.connect(self.add_test)

        self.retranslateUi(Test_Builder)
        QtCore.QMetaObject.connectSlotsByName(Test_Builder)

    def retranslateUi(self, Add_Test):
        _translate = QtCore.QCoreApplication.translate
        Add_Test.setWindowTitle(_translate("Test_Builder", "Dialog"))
        __sortingEnabled = self.listWidget.isSortingEnabled()
        self.listWidget.setSortingEnabled(False)
        self.listWidget.setSortingEnabled(__sortingEnabled)
        self.save_test_btn.setText(_translate("Test_Builder", "Save Tests"))
        self.discard_btn.setText(_translate("Test_Builder", "Discard"))
        self.add_test_btn.setText(_translate("Test_Builder", "Add New Test"))

    def add_test(self):
        try:
            self.new_window = QtWidgets.QDialog()
            ui = Ui_Add_Test(self.add_line)
            ui.setupUi(self.new_window)
            self.new_window.exec_()
        except Exception as e : dumpException(e)

    def add_line(self,test):
        self._test_list.append(test)
        _translate = QtCore.QCoreApplication.translate
        item = QtWidgets.QListWidgetItem()
        self.listWidget.addItem(item)
        item = self.listWidget.item(self._num_of_tests)
        item.setText(_translate("Test_Builder", f"{test['name']}"))
        self._num_of_tests += 1
    def discard(self):
        self.callback(None)
    def save_finish(self):
        self.callback(self._test_list)
if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_Test = QtWidgets.QDialog()
    ui = Ui_Test_Builder(lambda x: x)
    ui.setupUi(Add_Test)
    Add_Test.show()
    sys.exit(app.exec_())
