# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '.\win_questionnaire_condition.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from nodeeditor.utils import dumpException

questCounter = 0

class Ui_QuestionnaireDialog(object):
    def __init__(self, callback):
        super().__init__()
        self.callback = callback

    def setupUi(self, Dialog):
        self.window = Dialog
        Dialog.setObjectName("Dialog")
        Dialog.resize(701, 490)
        self.label = QtWidgets.QLabel(Dialog)
        self.label.setGeometry(QtCore.QRect(260, 80, 101, 21))
        self.label.setObjectName("label")
        self.questionnaire_answerNumber = QtWidgets.QSpinBox(Dialog)
        self.questionnaire_answerNumber.setGeometry(QtCore.QRect(350, 80, 42, 22))
        self.questionnaire_answerNumber.setObjectName("questionnaire_answerNumber")

        self.questionnaire_save = QtWidgets.QPushButton(Dialog)
        self.questionnaire_save.setGeometry(QtCore.QRect(40, 400, 101, 61))
        self.questionnaire_save.setObjectName("questionnaire_save")
        self.questionnaire_save.clicked.connect(self.save_condition)

        self.questionnaire_discard = QtWidgets.QPushButton(Dialog)
        self.questionnaire_discard.setGeometry(QtCore.QRect(160, 400, 101, 61))
        self.questionnaire_discard.setObjectName("questionnaire_discard")
        self.questionnaire_discard.clicked.connect(self.exit_window)

        self.label_2 = QtWidgets.QLabel(Dialog)
        self.label_2.setGeometry(QtCore.QRect(80, 80, 101, 21))
        self.label_2.setObjectName("label_2")

        self.questionnaire_questtionaire_number = QtWidgets.QSpinBox(Dialog)
        self.questionnaire_questtionaire_number.setGeometry(QtCore.QRect(180, 80, 42, 22))
        self.questionnaire_questtionaire_number.setObjectName("questionnaire_questtionaire_number")

        self.label_3 = QtWidgets.QLabel(Dialog)
        self.label_3.setGeometry(QtCore.QRect(80, 140, 121, 41))
        self.label_3.setObjectName("label_3")

        self.check_ans_1 = QtWidgets.QCheckBox(Dialog)
        self.check_ans_1.setGeometry(QtCore.QRect(80, 220, 41, 31))
        self.check_ans_1.setObjectName("check_ans_1")

        self.check_ans_2 = QtWidgets.QCheckBox(Dialog)
        self.check_ans_2.setGeometry(QtCore.QRect(130, 220, 41, 31))
        self.check_ans_2.setObjectName("check_ans_2")

        self.check_ans_3 = QtWidgets.QCheckBox(Dialog)
        self.check_ans_3.setGeometry(QtCore.QRect(180, 220, 41, 31))
        self.check_ans_3.setObjectName("check_ans_3")

        self.check_ans_4 = QtWidgets.QCheckBox(Dialog)
        self.check_ans_4.setGeometry(QtCore.QRect(230, 220, 41, 31))
        self.check_ans_4.setObjectName("check_ans_4")

        self.check_ans_6 = QtWidgets.QCheckBox(Dialog)
        self.check_ans_6.setGeometry(QtCore.QRect(330, 220, 41, 31))
        self.check_ans_6.setObjectName("check_ans_6")

        self.check_ans_5 = QtWidgets.QCheckBox(Dialog)
        self.check_ans_5.setGeometry(QtCore.QRect(280, 220, 41, 31))
        self.check_ans_5.setObjectName("check_ans_5")


        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "question no"))
        self.questionnaire_save.setText(_translate("Dialog", "Save"))
        self.questionnaire_discard.setText(_translate("Dialog", "Discard"))
        self.label_2.setText(_translate("Dialog", "questionnaire no"))
        self.label_3.setText(_translate("Dialog", "accepted answers:"))
        self.check_ans_1.setText(_translate("Dialog", "1"))
        self.check_ans_2.setText(_translate("Dialog", "2"))
        self.check_ans_3.setText(_translate("Dialog", "3"))
        self.check_ans_4.setText(_translate("Dialog", "4"))
        self.check_ans_6.setText(_translate("Dialog", "6"))
        self.check_ans_5.setText(_translate("Dialog", "5"))

    def acceptedAnswers(self):
        retList = []

        if(self.check_ans_1.isChecked()):
            retList.append(1)
        if(self.check_ans_2.isChecked()):
            retList.append(2)
        if(self.check_ans_3.isChecked()):
            retList.append(3)
        if(self.check_ans_4.isChecked()):
            retList.append(4)
        if(self.check_ans_5.isChecked()):
            retList.append(5)
        if(self.check_ans_6.isChecked()):
            retList.append(6)

        return retList

    def save_condition(self):
        try:
            global questCounter
            questCounter += 1
            q = {"title": "questionnaire condition " + str(questCounter),
               "type": "questionnaire condition",
               "questionnaireNumber": self.questionnaire_questtionaire_number.value(),
               "questionNumber": self.questionnaire_answerNumber.value(),
               "acceptedAnswers": self.acceptedAnswers()
               }
            self.callback(q)
            self.exit_window()

        except Exception as e:
            dumpException(e)

    def exit_window(self):
        self.window.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_QuestionnaireDialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
