# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nurse_gui.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(687, 422)
        self.widget = QtWidgets.QWidget(Dialog)
        self.widget.setGeometry(QtCore.QRect(-1, -1, 691, 421))
        self.widget.setObjectName("widget")
        self.partipant_id = QtWidgets.QLineEdit(self.widget)
        self.partipant_id.setGeometry(QtCore.QRect(50, 40, 171, 31))
        self.partipant_id.setObjectName("partipant_id")
        self.get_test_btn = QtWidgets.QPushButton(self.widget)
        self.get_test_btn.setGeometry(QtCore.QRect(240, 40, 81, 31))
        self.get_test_btn.setObjectName("get_test_btn")
        self.listWidget = QtWidgets.QListWidget(self.widget)
        self.listWidget.setGeometry(QtCore.QRect(50, 110, 501, 291))
        self.listWidget.setObjectName("listWidget")
        self.mark_as_done_btn = QtWidgets.QPushButton(self.widget)
        self.mark_as_done_btn.setGeometry(QtCore.QRect(570, 110, 81, 31))
        self.mark_as_done_btn.setObjectName("mark_as_done_btn")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.partipant_id.setPlaceholderText(_translate("Dialog", "participant id"))
        self.get_test_btn.setText(_translate("Dialog", "Get tests"))
        self.mark_as_done_btn.setText(_translate("Dialog", "Mark As Done"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog = QtWidgets.QDialog()
    ui = Ui_Dialog()
    ui.setupUi(Dialog)
    Dialog.show()
    sys.exit(app.exec_())
